# Generated by Django 5.2.6 on 2026-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
